<table>
    <thead>
        <tr>
            <th>name</th>
            <th>description</th>
            <th>event_day</th>
            <th>created_at</th>
        </tr>
    </thead>
    <tbody>
        @foreach($events as $event)
            <tr>
                <td>{{$event->name}}</td>
                <td>{{$event->description}}</td>
                <td>{{$event->event_day}}</td>
                <td>{{$event->created_at}}</td>
            </tr>
        @endforeach
    </tbody>
</table>